#line 2 "cipsycon.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 24
#define YY_END_OF_BUFFER 25
static yyconst short int yy_accept[288] =
    {   0,
        0,    0,   19,   19,    0,    0,    0,    0,    0,    0,
       25,   23,   16,   17,   23,   23,   18,   14,   23,    7,
       23,   23,   23,   23,   23,    1,   23,   23,   23,   23,
       13,    2,   23,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   10,   23,   19,   20,   22,   16,
        3,   23,    6,    9,   13,   11,   16,   17,   12,   14,
       12,    1,   15,    1,    1,    0,    0,   13,   13,   13,
       13,   13,   13,   13,   13,   12,   13,   13,   13,   13,
       13,   19,   21,   16,    0,    0,    3,   13,   14,   15,
        1,    0,    1,   13,   13,   13,   13,   13,   12,   12,

       13,   13,   13,   13,   13,   13,    0,    4,    0,    5,
        8,   14,   13,   13,   12,   13,   12,   13,   13,   13,
       13,   13,   13,   13,    4,    4,    4,    0,    5,    5,
        5,    0,   14,   13,   12,   13,   13,   13,   13,   13,
       13,   13,    4,    0,    4,    5,    0,    5,   14,   13,
       13,   12,   13,   13,   13,   14,   13,   13,   13,   13,
       13,   14,   13,   12,   13,   13,   14,   13,   13,   12,
       14,   13,   13,   14,   13,   12,   14,   13,   14,   13,
       14,   13,   14,   13,   14,   13,   14,   13,   14,   13,
       14,   13,   14,   13,   14,   13,   14,   13,   14,   13,

       14,   13,   14,   13,   14,   13,   14,   13,   14,   13,
       14,   13,   14,   13,   14,   13,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    9,   10,    9,   11,
       12,   13,   14,    9,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    9,    9,   19,
       20,   21,    9,   22,   23,   23,   23,   23,   24,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       25,    9,   26,   27,   28,    9,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   23,   38,   39,   40,   41,
       42,   23,   23,   43,   44,   45,   46,   23,   47,   23,
       23,   23,   48,   49,   50,    9,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    1,    2,    1,    3,    3,    4,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    5,    3,    3,
        3,    3,    5,    5,    3,    3,    3,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    3,    3,    3
    } ;

static yyconst short int yy_base[421] =
    {   0,
        0,    0,   48,   49,   55,   59,   41,   42,  540,  539,
      588,  591,   63,  591,  584,  566,  591,    0,  575,  591,
      564,   52,  563,   51,   53,   60,   60,  562,   62,   66,
        0,  591,  561,  537,   48,   48,   49,  545,  534,  532,
      543,   55,  531,  538,  591,  524,    0,  591,  565,   92,
       84,  568,  591,  591,   62,  591,  103,  591,  591,    0,
      550,  551,    0,   86,   93,   98,  548,    0,  534,  522,
      524,  520,  531,  519,  520,    0,  524,  514,  523,  520,
      519,    0,  591,  113,  104,  105,  110,  523,    0,    0,
      111,  536,  535,    0,  523,  518,  505,  516,  514,    0,

      516,  513,  499,  504,  498,  503,  523,  114,  522,  115,
      505,    0,    0,  500,    0,  500,  499,  489,  489,  490,
      489,  502,  499,  496,  510,  116,  127,  138,  509,  137,
      141,  148,    0,    0,    0,  485,  491,  483,  486,  475,
      480,  484,  140,  501,  500,  151,  499,  498,    0,    0,
      469,    0,  483,  471,  475,    0,    0,  478,  465,  468,
      464,    0,    0,    0,  470,  473,    0,    0,  463,    0,
        0,    0,  463,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  591,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  591,  591,  184,  187,  498,
      192,  195,  200,  497,  203,  496,  206,  495,  209,  197,

      212,  191,  215,  189,  218,  178,  221,  177,  224,  176,
      227,  175,  230,  174,  233,  173,  236,  172,  239,  171,
      242,  167,  245,  166,  248,  163,  251,  162,  254,  149,
      257,  145,  260,  141,  263,  137,  266,  136,  269,  132,
      272,  131,  275,  109,  278,   95,  281,   91,  284,   66,
      287,  290,  293,  296,  299,  302,  305,  308,  311,  314,
      317,  320,  323,  326,  329,  332,  335,  338,  341,  344,
      347,  350,  353,  356,  359,  362,  365,  368,  371,  374,
      377,  380,  383,  386,  389,  392,  395,  398,  401,  404,
      407,  410,  413,  416,  419,  422,  425,  428,  431,  434,

      437,  440,  443,  446,  449,  452,  455,  458,  461,  464,
      467,  470,  473,  476,  479,  482,  485,  488,  491,  494
    } ;

static yyconst short int yy_def[421] =
    {   0,
      287,    1,  288,  288,    1,    1,    1,    1,    1,    1,
      287,  287,  287,  287,  287,  287,  287,  289,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      290,  287,  287,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  290,  287,  287,  291,  287,  287,  287,
      287,  287,  287,  287,  290,  287,  287,  287,  287,  292,
      287,  287,  293,  287,  287,  287,  287,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  294,  294,  294,
      294,  291,  287,  287,  287,  287,  287,  294,  295,  293,
      287,  287,  287,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  287,  287,  287,  287,
      296,  297,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  287,  287,  287,  287,  287,  287,
      287,  287,  299,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  287,  287,  287,  287,  287,  287,  301,  302,
      302,  302,  302,  302,  302,  303,  304,  304,  304,  304,
      304,  305,  306,  306,  306,  306,  307,  308,  308,  308,
      309,  310,  310,  311,  312,  312,  313,  314,  315,  316,
      317,  318,  319,  320,  321,  322,  323,  324,  325,  326,
      327,  328,  329,  330,  331,  332,  333,  334,  335,  336,

      337,  338,  339,  340,  341,  342,  343,  344,  345,  346,
      347,  348,  349,  350,  351,  287,  352,  353,  354,  355,
      356,  357,  358,  359,  360,  361,  362,  363,  364,  365,
      366,  367,  368,  369,  370,  371,  372,  373,  374,  375,
      376,  377,  378,  379,  380,  381,  382,  383,  384,  385,
      386,  387,  388,  389,  390,  391,  392,  393,  394,  395,
      396,  397,  398,  399,  400,  401,  402,  403,  404,  405,
      406,  407,  408,  409,  410,  411,  412,  413,  414,  415,
      416,  417,  418,  419,  420,  287,    0,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287
    } ;

static yyconst short int yy_nxt[642] =
    {   0,
       12,   13,   14,   15,   13,   16,   17,   18,   12,   19,
       20,   12,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   31,   32,   12,   33,   12,   31,   34,
       35,   31,   36,   37,   31,   31,   38,   31,   31,   39,
       31,   40,   41,   42,   31,   43,   44,   45,   46,   12,
       48,   48,   54,   54,   49,   49,   50,   51,   52,   50,
       50,   51,   52,   50,   57,   61,   59,   57,   62,   63,
      216,   59,   59,   55,   55,   64,   70,   65,   59,   59,
       53,   59,   59,   66,   53,   59,   72,   67,   73,   71,
       74,   79,   66,   84,   75,  214,   84,   86,   86,  212,

       72,   80,   88,   91,   57,   85,   85,   57,   64,   66,
       65,   92,   92,  210,   84,   93,   66,   84,   66,  107,
      109,  108,  110,   86,   86,   66,   85,   85,   91,  126,
      130,  127,  131,  143,   66,  208,  206,  128,  132,  128,
      204,  202,  126,   66,  127,  200,  128,  132,  128,  198,
      128,  144,  144,  196,  146,  145,  130,  143,  131,  128,
      132,  147,  147,  128,  132,  148,  194,  192,  146,  132,
      190,  188,  128,  132,  132,  186,  184,  182,  180,  178,
      175,  172,  168,  132,   47,   47,   47,   47,   47,   60,
       60,   60,   82,  163,   82,  157,   82,   89,   89,   89,

       90,  150,   90,   90,   90,  112,  112,  112,  133,  133,
      133,  149,  149,  149,  156,  156,  156,  162,  162,  162,
      167,  167,  167,  171,  171,  171,  174,  174,  174,  177,
      177,  177,  179,  179,  179,  181,  181,  181,  183,  183,
      183,  185,  185,  185,  187,  187,  187,  189,  189,  189,
      191,  191,  191,  193,  193,  193,  195,  195,  195,  197,
      197,  197,  199,  199,  199,  201,  201,  201,  203,  203,
      203,  205,  205,  205,  207,  207,  207,  209,  209,  209,
      211,  211,  211,  213,  213,  213,  215,  215,  215,  217,
      217,  217,  218,  218,  218,  219,  219,  219,  220,  220,

      220,  221,  221,  221,  222,  222,  222,  223,  223,  223,
      224,  224,  224,  225,  225,  225,  226,  226,  226,  227,
      227,  227,  228,  228,  228,  229,  229,  229,  230,  230,
      230,  231,  231,  231,  232,  232,  232,  233,  233,  233,
      234,  234,  234,  235,  235,  235,  236,  236,  236,  237,
      237,  237,  238,  238,  238,  239,  239,  239,  240,  240,
      240,  241,  241,  241,  242,  242,  242,  243,  243,  243,
      244,  244,  244,  245,  245,  245,  246,  246,  246,  247,
      247,  247,  248,  248,  248,  249,  249,  249,  250,  250,
      250,  251,  251,  251,  252,  252,  252,  253,  253,  253,

      254,  254,  254,  255,  255,  255,  256,  256,  256,  257,
      257,  257,  258,  258,  258,  259,  259,  259,  260,  260,
      260,  261,  261,  261,  262,  262,  262,  263,  263,  263,
      264,  264,  264,  265,  265,  265,  266,  266,  266,  267,
      267,  267,  268,  268,  268,  269,  269,  269,  270,  270,
      270,  271,  271,  271,  272,  272,  272,  273,  273,  273,
      274,  274,  274,  275,  275,  275,  276,  276,  276,  277,
      277,  277,  278,  278,  278,  279,  279,  279,  280,  280,
      280,  281,  281,  281,  282,  282,  282,  283,  283,  283,
      284,  284,  284,  285,  285,  285,  286,  286,  286,  134,

      113,   94,   68,  176,  173,  170,  169,  166,  164,  165,
      164,  161,  160,  159,  158,  148,  148,  145,  145,  152,
      152,  155,  154,  153,  152,  151,  129,  125,  135,  142,
      135,  141,  140,  139,  138,  137,  136,  135,  118,  129,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  114,   93,   93,  111,  106,  105,  104,  103,  102,
      101,  100,   99,   98,   97,   96,   95,   59,   62,   59,
       87,   83,   59,   81,   76,   78,   77,   76,   76,   69,
       59,   59,   59,   59,   59,   59,   58,  287,   56,   56,
       11,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287
    } ;

static yyconst short int yy_chk[642] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    7,    8,    3,    4,    5,    5,    5,    5,
        6,    6,    6,    6,   13,   22,   24,   13,   24,   25,
      350,   22,   25,    7,    8,   26,   35,   26,   27,   27,
        5,   29,   29,   26,    6,   30,   36,   30,   36,   35,
       37,   42,   26,   50,   37,  348,   50,   51,   51,  346,

       55,   42,   55,   64,   57,   50,   50,   57,   65,   64,
       65,   66,   66,  344,   84,   66,   65,   84,   64,   85,
       86,   85,   86,   87,   87,   65,   84,   84,   91,  108,
      110,  108,  110,  126,   91,  342,  340,  108,  110,  126,
      338,  336,  127,   91,  127,  334,  108,  110,  126,  332,
      127,  128,  128,  330,  130,  128,  131,  143,  131,  127,
      130,  132,  132,  143,  131,  132,  328,  326,  146,  130,
      324,  322,  143,  131,  146,  320,  318,  316,  314,  312,
      310,  308,  306,  146,  288,  288,  288,  288,  288,  289,
      289,  289,  291,  304,  291,  302,  291,  292,  292,  292,

      293,  300,  293,  293,  293,  295,  295,  295,  297,  297,
      297,  299,  299,  299,  301,  301,  301,  303,  303,  303,
      305,  305,  305,  307,  307,  307,  309,  309,  309,  311,
      311,  311,  313,  313,  313,  315,  315,  315,  317,  317,
      317,  319,  319,  319,  321,  321,  321,  323,  323,  323,
      325,  325,  325,  327,  327,  327,  329,  329,  329,  331,
      331,  331,  333,  333,  333,  335,  335,  335,  337,  337,
      337,  339,  339,  339,  341,  341,  341,  343,  343,  343,
      345,  345,  345,  347,  347,  347,  349,  349,  349,  351,
      351,  351,  352,  352,  352,  353,  353,  353,  354,  354,

      354,  355,  355,  355,  356,  356,  356,  357,  357,  357,
      358,  358,  358,  359,  359,  359,  360,  360,  360,  361,
      361,  361,  362,  362,  362,  363,  363,  363,  364,  364,
      364,  365,  365,  365,  366,  366,  366,  367,  367,  367,
      368,  368,  368,  369,  369,  369,  370,  370,  370,  371,
      371,  371,  372,  372,  372,  373,  373,  373,  374,  374,
      374,  375,  375,  375,  376,  376,  376,  377,  377,  377,
      378,  378,  378,  379,  379,  379,  380,  380,  380,  381,
      381,  381,  382,  382,  382,  383,  383,  383,  384,  384,
      384,  385,  385,  385,  386,  386,  386,  387,  387,  387,

      388,  388,  388,  389,  389,  389,  390,  390,  390,  391,
      391,  391,  392,  392,  392,  393,  393,  393,  394,  394,
      394,  395,  395,  395,  396,  396,  396,  397,  397,  397,
      398,  398,  398,  399,  399,  399,  400,  400,  400,  401,
      401,  401,  402,  402,  402,  403,  403,  403,  404,  404,
      404,  405,  405,  405,  406,  406,  406,  407,  407,  407,
      408,  408,  408,  409,  409,  409,  410,  410,  410,  411,
      411,  411,  412,  412,  412,  413,  413,  413,  414,  414,
      414,  415,  415,  415,  416,  416,  416,  417,  417,  417,
      418,  418,  418,  419,  419,  419,  420,  420,  420,  298,

      296,  294,  290,  173,  169,  166,  165,  161,  160,  159,
      158,  155,  154,  153,  151,  148,  147,  145,  144,  142,
      141,  140,  139,  138,  137,  136,  129,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,  114,  111,  109,
      107,  106,  105,  104,  103,  102,  101,   99,   98,   97,
       96,   95,   93,   92,   88,   81,   80,   79,   78,   77,
       75,   74,   73,   72,   71,   70,   69,   67,   62,   61,
       52,   49,   46,   44,   43,   41,   40,   39,   38,   34,
       33,   28,   23,   21,   19,   16,   15,   11,   10,    9,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cipsycon.l"
#define INITIAL 0
/* scanner for Psycon syntax parser */
#line 3 "cipsycon.l"
#include <stdlib.h>
#include <string.h>
#include "psycon.yacc.h"
#include "cipsycon.tab.h"
#define strdup _strdup
#define LEX_STRING_MAX_INITIAL 1024

int LexStringLen = 0, LexStringMax = 0;
char *LexString = NULL;
int appendLexString(void);
#define YY_STACK_USED 1
#define STR 1

#define BRACKET 2

#define PARENTH 3

#define BRACE 4

#line 652 "cipsycon.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 24 "cipsycon.l"


	yylloc.first_line = yylloc.last_line;
	yylloc.first_column = yylloc.last_column;

#line 809 "cipsycon.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 288 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 591 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	yylval.dval = strtod(yytext, NULL);
	return T_NUMBER;
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "cipsycon.l"
{		/* opening bracket */
	yylloc.last_column += yyleng;
	yy_push_state(BRACKET);
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "cipsycon.l"
{
	++yylloc.last_line;
	yylloc.last_column = 1;
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	yylval.dval = strtod(yytext, NULL);
	return T_NUMBER;
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "cipsycon.l"
{
	++yylloc.last_line;
	yylloc.last_column = 1;
	yylval.dval = strtod(yytext, NULL);
	return T_NUMBER;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "cipsycon.l"
{	/* closing bracket */
	yylloc.last_column += yyleng;
	yy_pop_state();
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "cipsycon.l"
{	/* opening parenthesis */
	yylloc.last_column += yyleng;
	yy_push_state(PARENTH);
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	return T_ENDPOINT;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "cipsycon.l"
{	/* closing parenthesis */
	yylloc.last_column += yyleng;
	yy_pop_state();
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "cipsycon.l"
{	/* opening brace */
	yylloc.last_column += yyleng;
	yy_push_state(BRACE);
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "cipsycon.l"
{	/* closing brace */
	yylloc.last_column += yyleng;
	yy_pop_state();
	return (unsigned char)yytext[0];
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	return getTokenID(yytext);
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	yylval.str = strdup(yytext);
	return T_ID;
	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	yylval.str = strdup(yytext);
	return T_HOOKCMD;
	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 98 "cipsycon.l"
{	/* eat up a comment line */
	yylloc.last_column += yyleng;
	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "cipsycon.l"
{	/* eat up whitespace */
	yylloc.last_column += yyleng;
	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "cipsycon.l"
{
	++yylloc.last_line;
	yylloc.last_column = 1;
	return T_NEWLINE;
	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 109 "cipsycon.l"
{	/* start of a string */
	yylloc.last_column += yyleng;
	LexStringLen = 0;
	LexString[0] = '\0';
	yy_push_state(STR);
	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	if (appendLexString())
		return -1;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 120 "cipsycon.l"
{
	++yylloc.last_line;
	yylloc.last_column = 1;
	if (appendLexString())
		return -1;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	yyleng = 1;
	if (appendLexString())
		return -1;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 132 "cipsycon.l"
{	/* end of a string */
	yylloc.last_column += yyleng;
	yy_pop_state();
	yylval.str = strdup(LexString);
	return T_STRING;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 138 "cipsycon.l"
{
	yylloc.last_column += yyleng;
	return (unsigned char)yytext[0];
	/* printf( "Unrecognized character: %s\n", yytext ); */
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 143 "cipsycon.l"
ECHO;
	YY_BREAK
#line 1102 "cipsycon.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
case YY_STATE_EOF(BRACKET):
case YY_STATE_EOF(PARENTH):
case YY_STATE_EOF(BRACE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 288 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 288 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 287);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 143 "cipsycon.l"

int appendLexString(void)
{
	if (LexStringMax < LexStringLen + yyleng + 1) {
		LexStringMax *= 2;
		LexString = (char *)realloc(LexString, LexStringMax);
		if (LexString == NULL)
			return 2;
	}
	strncpy_s(LexString+LexStringLen, LexStringMax-LexStringLen, yytext, yyleng);
	LexStringLen += yyleng;
	LexString[LexStringLen] = '\0';
	return 0;
}

int yysetNewStringToScan(const char *source)
{
	if (LexStringMax != LEX_STRING_MAX_INITIAL) {
		/* (re)initialize LexString and LexStringMax - can be shrinking for memory efficiency */
		LexStringMax = LEX_STRING_MAX_INITIAL;
		LexString = (char *)realloc(LexString, LexStringMax);
		if (LexString == NULL)
			return 2;
	}
	yyrestart(NULL);
	yy_delete_buffer(YY_CURRENT_BUFFER);
	yy_scan_string(source);
	BEGIN(INITIAL);
	yylloc.last_line = yylloc.first_line = 1;
	yylloc.last_column = yylloc.first_column = 1;
	return 0;
}

int yysetNewFileToScan(FILE *source)
{
	if (LexStringMax != LEX_STRING_MAX_INITIAL) {
		/* (re)initialize LexString and LexStringMax - can be shrinking for memory efficiency */
		LexStringMax = LEX_STRING_MAX_INITIAL;
		LexString = (char *)realloc(LexString, LexStringMax);
		if (LexString == NULL)
			return 2;
	}
	yy_delete_buffer(YY_CURRENT_BUFFER);
	yyrestart(source);
	BEGIN(INITIAL);
	yylloc.last_line = yylloc.first_line = 1;
	yylloc.last_column = yylloc.first_column = 1;
	return 0;
}